config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  resources :channels do
    resources :episodes do
      resources :comments do
        resources :comments
      end
    end
    resources :playlists
  end

  # resources :comments do
  #   resources :comments
  # end

  resources :tags, only: :create
  resources :likes, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  resources :playlists
  
  get '/@:username', to: 'profiles#show', as: :profile
  get '/@:username/edit', to: 'profiles#update', as: :edit_profile

  put '/@:username', to: 'profiles#update'

  get '/@:username/subscriptions', to: 'profiles#user_subscriptions', as: :user_subs
  get '/@:username/about', to: 'profiles#about_user', as: :about_user
  get '/@:username/likes', to: 'profiles#user_likes', as: :user_likes
  get '/@:username/likes/comments', to: 'profiles#user_comment_likes', as: :user_comment_likes

  get '/channels/:id/channels', to: 'channels#owned_channels', as: :owned_channels
  get '/channels/:id/subscriptions', to: 'channels#channel_subscriptions', as: :channel_subs
  get '/channels/:id/about', to: 'channels#about_channel', as: :about_channel
  
  get '/channels/:channel_id/episodes/:id/related', to: 'episodes#related_episodes', as: :related_episodes

  get '/library', to: 'profiles#library', as: :library
  get '/history', to: 'profiles#history', as: :history
  get '/trending', to: 'profiles#trending', as: :trending
end

app/models/channel.rb
# == Schema Information
#
# Table name: channels
#
#  id                  :bigint           not null, primary key
#  description         :text
#  location            :string
#  name                :string
#  playlists_count     :integer          default(0), not null
#  slug                :string
#  subscriptions_count :integer          default(0), not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :bigint           not null
#
# Indexes
#
#  index_channels_on_name     (name) UNIQUE
#  index_channels_on_slug     (slug) UNIQUE
#  index_channels_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Channel < ApplicationRecord

  belongs_to :user

  extend FriendlyId
  friendly_id :formatted_name, use: :slugged

  def formatted_name
    "@ #{name.downcase}"
  end

  def normalize_friendly_id(string)
    string.gsub(" ", "")
  end
  
  def slug=(value)
    if value.present?
      write_attribute(:slug, value)
    end
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

  validates :name, presence: true, length: { minimum: 3 }, uniqueness: { case_sensitive: false }
  validates :description, :location, presence: true

  has_many :episodes, dependent: :destroy
  has_many :playlists, dependent: :destroy
  has_many :subscriptions, as: :subscribable, dependent: :destroy
  has_many :subscribed_users, through: :subscriptions, source: :user

  has_one_attached :cover_image do |attachable|
    attachable.variant :display, resize_to_fill: [1920, 500]
  end

  validates :cover_image, presence: true,   content_type: { in: %w[image/jpeg image/png],
                                      message: "must be a valid image format" },
                      size:         { less_than: 1.megabytes,
                                      message:   "should be less than 1MB" }
  
  has_one_attached :avatar do |attachable|
    attachable.variant :display, resize_to_limit: [500, 500]
  end

  validates :avatar, presence: true,   content_type: { in: %w[image/jpeg],
                                      message: "must be a valid image format" },
                      size:         { less_than: 1.megabytes,
                                      message:   "should be less than 1MB" }
  
  private
  
  def downcase_name
    self.name.downcase!
  end

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
    before_action :set_channel, only: [:show, :edit, :update, :destroy, :owned_channels, :channel_subscriptions, :about_channel]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :correct_user, only: %i[ edit update destroy ]
    # before_action :allow_one_channel_creation, only: %i[ new create ]

    def index
        @channels = Channel.all.includes(:episodes)
    end

    def show
        
    end

    def new
        @channel = Channel.new
    end

    def create
        @channel = current_user.channels.build(channel_params)
        if @channel.save
            respond_to do |format|
                format.html { redirect_to @channel, notice: 'Channel was successfully created'}
            end
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        
    end

    def update
        if @channel.update(channel_params)
            respond_to do |format|
                format.html { redirect_to @channel, notice: 'Channel was updated successfully'}
            end
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @channel.destroy
        respond_to do |format|
            format.html { redirect_to channels_path, notice: 'Channel was deleted successfully'}
        end
    end

    def owned_channels
        @owned_channels ||= @channel.user.channels.includes(:episodes).where.not(id: @channel)
    end

    def channel_subscriptions
        @subscriptions = @channel.user.subscribed_channels
    end

    def about_channel
        
    end

    private

    def channel_params
        params.require(:channel).permit(:name, :description, :location, :cover_image, :avatar)
    end

    def set_channel
        @channel ||= Channel.friendly.find(params[:id])
    end

    # confirms the correct user
    def correct_user
        @channel ||= Channel.friendly.find(params[:id])
        redirect_to(channels_url, status: :see_other, notice: "Access denied") unless current_user == @channel.user
    end

    # create channel only once
    def allow_one_channel_creation
        redirect_to(root_url, status: :see_other, notice: "You can only create a channel per account") unless current_user.channels.count < 1
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
    def channel_nav_page?(link_name)
        return "text-dark" if controller_name == link_name
    end

    def channel_link_page?(link_name, link_action)
        return "text-dark" if controller_name == link_name && action_name == link_action
    end

    def channel_layout_renderer(controller_name, action_name)
        render 'channels/channel_layout_content' if controller_name == controller_name && action_name == action_name
    end
end

app/views/channels/_channel.html.erb
<div class="col-md-3">
    <%= link_to channel, title: channel.name, class: "text-decoration-none" do %>
        <div class="card border-0 p-0 m-0 text-center">
            <%# check if episode cover_image is present, else display default cover_image %>
            <%= image_tag(channel.avatar, class: "img-fluid rounded-circle mx-auto") if channel.avatar.attached? %>
            <div class="card-body px-0">
                <h5 class="card-title fw-bold mb-0" style="font-size: 1rem;"><%= channel.name.truncate(65) %></h5>
                <p class="card-text text-secondary"><small><span><%= pluralize(number_with_delimiter(channel.subscribed_users.count, delimiter: ','), 'subscriber') %></span></small></p>

                <% if controller_name == 'channels' && action_name != 'index' %>
                    <% if @channel.user != current_user %>
                        <%= render 'subscriptions/subscription_button', subscribable: @channel %>
                    <% end %>
                <% else %>
                    <% if channel.user != current_user %>
                        <%= render 'subscriptions/subscription_button', subscribable: channel %>
                    <% end %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/channels/_channel_header.html.erb
<!--<div class="channel" style="height: 28vh; background-image: url(<%= rails_blob_url(@channel.cover_image) %>); background-color: #000; background-repeat: no-repeat, repeat; background-position: center; background-size: 100%;"></div>-->  
<div>
    <%= image_tag(@channel.cover_image.variant(:display), class: "img-fluid back") %>
</div>

<div class="container" style="max-width: 90%">
    <div class="d-flex my-4">
        <div class="avatar">
            <%= link_to image_tag(@channel.avatar, size: "140x140", class: "rounded rounded-circle"), profile_path(@channel.user.username) if @channel.avatar.attached? %>
        </div>

        <div class="channel-info ms-4 w-50">

            <h1 class="fw-bold"><%= @channel.name.titleize %></h1>

            <p class="text-secondary">
                <span class="me-2"><%= @channel.slug %></span> 
                <span class="ms-2"><%= pluralize(number_with_delimiter(@channel.subscribed_users.count, delimiter: ','), 'subscriber') %></span> 
                <span class="ms-2"><%= pluralize(number_with_delimiter(@channel.episodes.count, delimiter: ','), 'episode') %></span>
            </p>

            <p><%= link_to about_channel_path(@channel), class: "text-secondary text-decoration-none" do %>
                <%= @channel.description.truncate(75) %>
                <i class="bi bi-chevron-right"></i></p>
            <% end %> 
        </div>

        <%= render partial: 'channels/sub_edit_btn' %>
    </div>
</div>

<%= render partial: "channels/channel_nav" %>

<hr>

app/views/channels/_channel_layout_renderer.html.erb
<% if controller_name == "channels" && action_name == "show" %>
    <%= render 'channels/page_contents/channel_show_content' %>

<% elsif controller_name == "channels" && action_name == "index" %>
    <%= render 'channels/page_contents/channels_index_content' %>

<% elsif controller_name == "episodes" && action_name == "index" %>
    <%= render 'channels/page_contents/channel_episodes_content' %>

<% elsif controller_name == "playlists" && action_name == "index" %>
    <%= render 'channels/page_contents/channel_playlists_content' %>

<% elsif controller_name == "channels" && action_name == "owned_channels" %>
    <%= render 'channels/page_contents/channel_channels_content' %>

<% elsif controller_name == "channels" && action_name == "channel_subscriptions" %>
    <%= render 'channels/page_contents/channel_subscriptions_content' %>

<% elsif controller_name == "channels" && action_name == "about_channel" %>
    <%= render 'channels/page_contents/about_channel_content' %>
<% end %>

app/views/channels/_channel_nav.html.erb
<ul class="nav justify-content-between container fw-bold channel-nav text-uppercase">
    <li class="nav-item">
        <%= link_to 'Home', @channel, class: "nav-link text-secondary #{ 'text-dark' if controller_name == 'channels' && action_name == 'show' }" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Episodes', channel_episodes_path(@channel), class: "nav-link text-secondary #{channel_nav_page?("episodes")}" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Playlists', channel_playlists_path(@channel), class: "nav-link text-secondary #{channel_nav_page?("playlists")}" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Channels', owned_channels_path(@channel), class: "nav-link text-secondary #{ 'text-dark' if controller_name == 'channels' && action_name == 'owned_channels' }" %>
    </li>
    </li>
    <li class="nav-item">
        <%= link_to 'Subscriptions', channel_subs_path(@channel), class: "nav-link text-secondary #{ 'text-dark' if controller_name == 'channels' && action_name == 'channel_subscriptions'}" %>
    </li>
    </li>
    <li class="nav-item">
        <%= link_to 'About', about_channel_path(@channel), class: "nav-link text-secondary #{ 'text-dark' if controller_name == 'channels' && action_name == 'about_channel'}" %>
    </li>
</ul>

app/views/channels/_form.html.erb
<%= form_with model: [channel] do |f| %>
    <%= render 'layouts/errors', f: f %>

    <div class="mb-3">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="mb-3">
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <div class="mb-3">
        <%= f.label :location %>
        <%= f.text_field :location %>
    </div>

    <div class="mb-3">
        <%= f.label :cover_image %>
        <%= f.file_field :cover_image %>
    </div>

    <div class="mb-3">
        <%= f.label :avatar %>
        <%= f.file_field :avatar %>
    </div>

    <div class="mb-3">
        <%= f.submit %>
    </div>
<% end %>

app/views/channels/_sidebar.html.erb
<section class="mx-2 mb-4">
    <!-- sidebar section 1 starts -->
    <ul class="list-unstyled sidebar-list list-1" >
        <li>
            <%= link_to '#', class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block", style: "width: auto" do %>
                <i class="bi bi-house-door me-3 fs-5"></i>
                Home
            <% end %>
        </li>

        <li>
            <%= link_to user_subs_path(current_user.username), class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block #{ 'bg-secondary-subtle' if controller_name == 'profiles' && action_name == 'user_subscriptions'}", style: "width: auto" do %>
                <i class="bi bi-collection-play me-3 fs-5"></i>
                Subscriptions
            <% end %>
        </li>

    </ul>
    <!-- sidebar section 1 end -->

    <!-- sidebar section 2 starts -->
    <ul class="list-unstyled sidebar-list list-2" >
        <hr class="my-3">

        <li>
            <%= link_to library_path, class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block #{ 'bg-secondary-subtle' if controller_name == 'profiles' && action_name == 'library'}", style: "width: auto" do %>
                <i class="bi bi-collection me-3 fs-5"></i>
                Library
            <% end %>
        </li>

        <li>
            <%= link_to history_path, class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block #{ 'bg-secondary-subtle' if controller_name == 'profiles' && action_name == 'history'}", style: "width: auto" do %>
                <i class="bi bi-clock-history me-3 fs-5"></i>
                History
            <% end %>
        </li>

        <li>
            <%= link_to profile_path(current_user.username), class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block #{ 'bg-secondary-subtle' if controller_name == 'profiles' && action_name == 'show'}", style: "width: auto" do %>
                <i class="bi bi-file-music me-3 fs-5"></i>
                Your channels
            <% end %>
        </li>

        <li>
            <%= link_to '#', class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block", style: "width: auto" do %>
                <i class="bi bi-clock me-3 fs-5"></i>
                Watch later
            <% end %>
        </li>

        <li>
            <%= link_to user_likes_path(current_user.username), class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block #{ 'bg-secondary-subtle' if controller_name == 'profiles' && action_name == 'user_likes'}", style: "width: auto" do %>
                <i class="bi bi-heart me-3 fs-5"></i>
                Liked episodes
            <% end %>
        </li>
    </ul>
    <!-- sidebar section 2 ends -->

    <!-- sidebar subscriptions section starts -->
    <ul class="list-unstyled sidebar-list list-3" >

        <hr class="my-3">

        <h6 class="text-dark py-1 ps-3 pe-5 rounded-3 d-block fw-bold" style="width:auto">Subscriptions</h6>
        <% current_user.subscribed_channels.each do |channel| %>
            <li>
                <%= link_to channel, class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block", style: "width: auto" do %>
                    <%= image_tag(channel.avatar, style: "height: 30px; width: 30px", class: "rounded-circle me-3 my-1") %>
                    <%= channel.name.truncate(17) %>
                <% end %>
            </li>
        <% end %>
        
        <li>
            <%= link_to user_subs_path(current_user.username), class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block", style: "width: auto" do %>
                <i class="bi bi-chevron-down me-3 fs-5"></i>
                Show more
            <% end %>
        </li>
    </ul>
    <!-- sidebar subscriptions section end -->

    <!-- sidebar explore section starts -->

    <ul class="list-unstyled sidebar-list list-4" >

        <hr class="my-3">

        <h6 class="text-dark py-1 ps-3 pe-5 d-block fw-bold">Explore</h6>

        <li>
            <%= link_to channels_path, class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block #{ 'bg-secondary-subtle' if controller_name == 'channels' && action_name == 'index'}", style: "width: auto" do %>
                <i class="bi bi-table me-3 fs-5"></i>
                All channels
            <% end %>
        </li>

        <li>
            <%= link_to trending_path, class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block #{ 'bg-secondary-subtle' if controller_name == 'profiles' && action_name == 'trending'}", style: "width: auto" do %>
                <i class="bi bi-fire me-3 fs-5"></i>
                Trending
            <% end %>
        </li>

        <li>
            <%= link_to '#', class: "text-decoration-none text-dark py-1 ps-3 pe-5 rounded-3 d-block", style: "width: auto" do %>
                <i class="bi bi-tags me-3 fs-5"></i>
                Tags
            <% end %>
        </li>

    </ul>

    <!-- sidebar explore section ends -->
</section>

app/views/channels/_sub_edit_btn.html.erb
<div class="button ms-auto">
    <% if @channel.user == current_user %>
        <p><%= link_to 'Edit profile', '#', class: "btn btn-success rounded rounded-5" %> </p>
    <% else %>
        <p><%= render 'subscriptions/subscription_button', subscribable: @channel %></p>
    <% end %>
</div>

app/views/channels/about_channel.html.erb
<% provide(:title, "About #{@channel.name}") %>

<!-- layout for channel page and subpages and subpages i.e channels home, episodes, subscriptions etc.. -->
<%= render 'channels/shared/channel_layout' %>

app/views/channels/channel_subscriptions.html.erb
<% provide(:title, "#{@channel.name}'s subscriptions".html_safe) %>

<!-- layout for channel page and subpages and subpages i.e channels home, episodes, subscriptions etc.. -->
<%= render 'channels/shared/channel_layout' %>

app/views/channels/edit.html.erb
<% provide(:title, "Edit channel") %>

<h1>Edit channel</h1>

<%= render 'form', channel: @channel %>

app/views/channels/index.html.erb
<% provide(:title, "All channels") %>

<!-- layout for channel page and subpages i.e channels home, episodes, subscriptions etc.. -->
<%= render 'channels/shared/channel_layout' %>

app/views/channels/new.html.erb
<% provide(:title, "New channel") %>

<h1>New channel</h1>

<%= render 'form', channel: @channel %>

app/views/channels/owned_channels.html.erb
<% provide(:title, "#{@channel.name}'s channels".html_safe) %>

<!-- layout for channel page and subpages and subpages i.e channels home, episodes, subscriptions etc.. -->
<%= render 'channels/shared/channel_layout' %>

app/views/channels/show.html.erb
<% provide(:title, (@channel.name).html_safe) %>

<!-- layout for channel page and subpages i.e channels home, episodes, subscriptions etc.. -->
<%= render 'channels/shared/channel_layout' %>