config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  resources :channels do
    resources :episodes do
      resources :comments do
        resources :comments
      end
    end
    resources :playlists
  end

  # resources :comments do
  #   resources :comments
  # end

  resources :tags, only: :create
  resources :likes, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  resources :playlists
  
  get '/@:username', to: 'profiles#show', as: :profile
  get '/@:username/edit', to: 'profiles#update', as: :edit_profile

  put '/@:username', to: 'profiles#update'

  get '/@:username/subscriptions', to: 'profiles#user_subscriptions', as: :user_subs
  get '/@:username/about', to: 'profiles#about_user', as: :about_user
  get '/@:username/likes', to: 'profiles#user_likes', as: :user_likes
  get '/@:username/likes/comments', to: 'profiles#user_comment_likes', as: :user_comment_likes

  get '/channels/:id/channels', to: 'channels#owned_channels', as: :owned_channels
  get '/channels/:id/subscriptions', to: 'channels#channel_subscriptions', as: :channel_subs
  get '/channels/:id/about', to: 'channels#about_channel', as: :about_channel
  
  get '/channels/:channel_id/episodes/:id/related', to: 'episodes#related_episodes', as: :related_episodes

  get '/library', to: 'profiles#library', as: :library
  get '/history', to: 'profiles#history', as: :history
  get '/trending', to: 'profiles#trending', as: :trending
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :bigint           not null, primary key
#  body             :text             not null
#  commentable_type :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  commentable_id   :bigint           not null
#  parent_id        :integer
#  user_id          :bigint           not null
#
# Indexes
#
#  index_comments_on_commentable  (commentable_type,commentable_id)
#  index_comments_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  validates :body, presence: true
  
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_commentable, only: [:new, :create, :edit, :update, :destroy]
    before_action :find_channel
    before_action :correct_user, only: [:edit, :update, :destroy]
    before_action :find_comment, only: [:edit, :update, :destroy]

    def new
        @comment = Comment.new
            @parent ||= Comment.find(params[:comment_id])
    end

    def create
        @comment = @commentable.comments.build(comment_params)
        @comment.user = current_user

        if @comment.save
            respond_to do |format|
                format.html { redirect_to channel_episode_url(@channel, @commentable), notice: 'Comment created!' }
            end
        else
            flash[:notice] = @comment.errors.full_messages.to_sentence
            redirect_back(fallback_location: channel_episode_url(@channel, @commentable), status: :see_other)
        end
    end

    def edit
    end

    def update
        if @comment.update(comment_params)
            respond_to do |format|
                if @comment.commentable_type == 'Episode'
                    format.html { redirect_to channel_episode_url(@channel, @commentable), notice: 'Comment updated!' }
                end
            end
        else
            flash[:notice] = @comment.errors.full_messages.to_sentence
            redirect_back(fallback_location: channel_episode_url(@channel, @commentable), status: :see_other)
        end 
    end

    def destroy
        @comment.destroy
        respond_to do |format|
            format.html { redirect_to channel_episode_path(@channel, @commentable), notice: "Comment deleted!" }
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:body, :parent_id)
    end

    def find_comment
        @comment ||= Comment.find(params[:id])
    end

    def find_parent
        @parent ||= Comment.find(params[:comment_id])
    end

    def find_commentable
        if params[:episode_id].present?
            @commentable ||= Episode.find(params[:episode_id])
        end
    end

    def find_channel
        if params[:channel_id].present?
            @channel ||= Channel.friendly.find(params[:channel_id])
        end
    end

    # confirms the correct user
    def correct_user
        @comment ||= Comment.find(params[:id])
        redirect_to(channel_episode_path(@channel, @commentable), status: :see_other, notice: "Access denied") unless @comment.user == current_user
    end
end

app/helpers/comments_helper.rb
module CommentsHelper

    def comment_user_or_channel_avatar(user, comment, channel)
        # Display proper avatars for channel owner and ordinary user and reduce avatar size if comment.parent is nil
        if user == comment.commentable.user
            if !comment.parent
                link_to image_tag(channel.avatar, class: "img-fluid rounded-circle me-3", style: "width: 45px; height: 45px;"), channel
            else
                link_to image_tag(channel.avatar, class: "img-fluid rounded-circle me-3", style: "width: 35px; height: 35px;"), channel
            end
        else 
            if !comment.parent
                # todo: change to comment user's avatar
                link_to image_tag('avatar.jpg', class: "img-fluid rounded-circle me-3", style: "width: 45px; height: 45px;"), profile_path(user.username)
            else
                link_to image_tag('avatar.jpg', class: "img-fluid rounded-circle me-3", style: "width: 35px; height: 35px;"), profile_path(user.username)
            end
        end 
    end

    def comment_user_or_channel_name(user, comment, channel)
        if user == comment.commentable.user
            link_to channel.name, '#', class: "btn btn-sm btn-secondary rounded-5 py-0"
        else
            link_to user.username, '#', class: "text-decoration-none text-dark"
        end
    end
end

app/views/comments/_comment.html.erb
<!-- single comment partial -->
<div class="d-flex my-2">
    <!-- comment user avatar -->
    <%= comment_user_or_channel_avatar(comment.user, comment, @channel) %>
    <!-- comment user avatar ends -->

    <!-- comment content -->
    <div class="content">
        <small>
            <span><%= comment_user_or_channel_name(comment.user, comment, @channel) %></span> 
            
            <span class="text-secondary"><small><%= time_ago_in_words(comment.created_at) %> ago</small></span>
        </small>

        <p class="my-1"><%= comment.body %></p>

        <!-- comment footer -->
        <div class="comment-footer">
            <!-- comment actions -->
            <small>
                <span class="text-secondary">578 likes</span> 

                <span><%= link_to 'Reply', new_channel_episode_comment_comment_path(@channel, @commentable, comment, parent: @comment), class: "btn btn-sm btn-transparent" %></span>

                <% if comment.commentable == @episode && comment.user == current_user %>
                    <span><%= link_to 'Edit', edit_channel_episode_comment_path(@channel, @episode, comment), class: "btn btn-sm btn-transparent" %></span>
                    
                    <span><%= link_to 'Delete', channel_episode_comment_path(@channel, @episode, comment), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-sm btn-transparent"  %></span>
                <% end %>

            </small>
            
            <!-- comment actions end -->
        </div>
        <!-- comment footer ends -->

        <!-- comment replies count -->
        <% if comment.comments.present? %>
            <div>
                <%= link_to '#', class: "text-decoration-none" do %>
                    <small>
                        <i class="bi bi-chevron-down text-dark me-2"></i>
                        <%= pluralize(number_with_delimiter(comment.comments.count, delimiter: ','), 'reply') %>
                    </small>
                <% end %>
            </div>
        <% end %>

    </div>
    <!-- comment content ends -->
</div>

    <div class="sub-comment ms-5">
        <%= render comment.comments.order(id: :desc) %>
    </div>
    <%#= render partial: 'comments/form', locals: { channel: @channel, commentable: @commentable, comment: @comment, parent: comment } %>

app/views/comments/_form.html.erb
<%= form_with model: [channel, commentable, comment] do |f| %>
    <%= render 'layouts/errors', f: f %>

    <% if !parent.nil? %>
        <%= f.hidden_field :parent_id, value: parent.id %>
    <% end %>

    <div>
        <%= f.text_area :body, placeholder: 'Add a comment', class: "form-control w-100" %>
    </div>

    <div class="text-end">
        <% if !parent.nil? %>
            <%= f.button 'Reply', class: "btn btn-dark mt-2 rounded-5" %>
        <% else %>
            <%= f.button 'Submit', class: "btn btn-dark mt-2 rounded-5" %>
        <% end %>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit comment</h1>

<%= render partial: 'comments/form', locals: { channel: @commentable.channel, commentable: @commentable, comment: @comment, parent: nil } %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render partial: 'form', locals: { channel: @channel, commentable: @commentable, comment: @comment, parent: @parent } %>