config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  resources :channels do
    resources :episodes do
      resources :comments do
        resources :comments
      end
    end
    resources :playlists
  end

  # resources :comments do
  #   resources :comments
  # end

  resources :tags, only: :create
  resources :likes, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  resources :playlists
  
  get '/@:username', to: 'profiles#show', as: :profile
  get '/@:username/edit', to: 'profiles#update', as: :edit_profile

  put '/@:username', to: 'profiles#update'

  get '/@:username/subscriptions', to: 'profiles#user_subscriptions', as: :user_subs
  get '/@:username/about', to: 'profiles#about_user', as: :about_user
  get '/@:username/likes', to: 'profiles#user_likes', as: :user_likes
  get '/@:username/likes/comments', to: 'profiles#user_comment_likes', as: :user_comment_likes

  get '/channels/:id/channels', to: 'channels#owned_channels', as: :owned_channels
  get '/channels/:id/subscriptions', to: 'channels#channel_subscriptions', as: :channel_subs
  get '/channels/:id/about', to: 'channels#about_channel', as: :about_channel
  
  get '/channels/:channel_id/episodes/:id/related', to: 'episodes#related_episodes', as: :related_episodes

  get '/library', to: 'profiles#library', as: :library
  get '/history', to: 'profiles#history', as: :history
  get '/trending', to: 'profiles#trending', as: :trending
end

app/models/episode.rb
# == Schema Information
#
# Table name: episodes
#
#  id          :bigint           not null, primary key
#  description :text
#  likes_count :integer          default(0), not null
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  channel_id  :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_episodes_on_channel_id  (channel_id)
#  index_episodes_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (channel_id => channels.id)
#  fk_rails_...  (user_id => users.id)
#
class Episode < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  belongs_to :channel

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :episode_playlists, dependent: :destroy
  has_many :playlists, through: :episode_playlists

  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  has_one_attached :audio

  has_one_attached :image

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    before_action :find_channel
    before_action :find_episode, only: [:show, :edit, :update, :destroy, :related_episodes]
    before_action :restrict_other_users, only: %w[edit update destroy]
    before_action :restrict_channel_episode_creation, only: [:new, :create]

    def index
        @episodes = @channel.episodes
    end

    def show
        @playlist = Playlist.new
        @commentable = @episode
        @comment = Comment.new
        @episodes_from_channel = @episode.channel.episodes.where.not(id: @episode)
    end

    def new
        @episode = Episode.new
    end

    def create
        @episode = @channel.episodes.build(episode_params)
        @episode.user = current_user
        if @episode.save
            respond_to do |format|
                format.html { redirect_to channel_episode_path(@channel, @episode), notice: 'Episode was successfully created.'}
                # format.turbo_stream { flash.now[:notice] = 'episode was successfully created.' }
            end
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        
    end

    def update
        if @episode.update(episode_params)
            respond_to do |format|
                format.html { redirect_to channel_episode_path(@channel, @episode), notice: "Episode was successfully updated." }
                # format.turbo_stream { flash.now[notice:] = "episode was successfully updated." }
            end
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @episode.destroy
        respond_to do |format|
            format.html { redirect_to @channel, notice: "Episode deleted." }
            # format.turbo_stream { flash.now[:notice] = "episode deleted." }
        end
    end

    def related_episodes
        @related_episodes ||= @episode.tags
        if params[:episode_id].present?
            @commentable ||= Episode.find(params[:episode_id])
        end
        render :show, status: :unprocessable_entity
    end

    private

        def episode_params
            params.require(:episode).permit(:title, :description, :channel_id, :image, :audio, :user_id, tag_ids: [], playlist_ids: [])
        end

        def find_episode
            @episode ||= Episode.find(params[:id])
        end

        def find_channel
            @channel ||= Channel.friendly.find(params[:channel_id])
        end

        def restrict_other_users
            redirect_to(@channel, status: :see_other, notice: 'Access denied') unless current_user == @episode.user
        end

        def restrict_channel_episode_creation
            redirect_to(@channel, status: :see_other, notice: 'Access denied') if @channel.user != current_user
        end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_episode.html.erb
<div class="col-md-3">
    <%= link_to channel_episode_path(@channel, episode), title: episode.title, class: "text-decoration-none" do %>
        <div class="card border-0 p-0 m-0">
            <%# check if episode image is present, else display default image %>
            <% if episode.image.attached? %>
                <%= image_tag(episode.image, class: "card-img-top rounded-3") %>
            <% else %>
                <%= image_tag('default-episode-image.jpg', class: "card-img-top rounded-3") %>
            <% end %>  
            <div class="card-body px-0">
                <h5 class="card-title fw-bold" style="font-size: 1rem;"><%= episode.title.truncate(65) %></h5>
                <p class="card-text text-secondary"><small><span><%= pluralize(number_with_delimiter(200000, delimiter: ','), 'view') %></span> <span class="mx-1">•</span> <span><%= time_ago_in_words(episode.created_at) %> ago</span></small></p>
            </div>
        </div>
    <% end %>
</div>

app/views/episodes/_form.html.erb
<%= form_with model: [channel, episode] do |f| %>
    <%= render 'layouts/errors', f: f %>

    <div class="mb-3">
        <strong><%= f.label :title %></strong>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
        <strong><%= f.label :description %></strong>
        <%= f.text_area :description, class: "form-control rounded",
                            placeholder: "Episode description" %>
    </div>

    <div class="mb-3">
        <strong><%= f.label :image %></strong>
        <%= f.file_field :image, class: "form-control rounded" %>
    </div>

    <div class="mb-3">
        <strong><%= f.label :upload_audio_file %></strong>
        <%= f.file_field :audio, class: "form-control rounded" %>
    </div>

    <div class="mb-3" data-controller="tom-select">
        <h5><%= f.label :tags, class: "form-label" %></h5>
        <%= f.select :tag_ids, Tag.all.pluck(:name, :id), {}, { multiple: true, id: "select-tags" } %>
    </div>

    <div class="mb-3" data-controller="tom-select-playlist">
        <h5><%= f.label :playlists, class: "form-label" %></h5>
        <%= f.select :playlist_ids, channel.playlists.pluck(:name, :id), {}, { multiple: true, id: "select-playlists" } %>
    </div>

    <div class="actions">
        <%= f.submit "Upload episode", class: "btn btn-dark" %>
        <% if !(f.object.new_record?) %>
            <%= link_to "Cancel", channel_episode_path(@channel, @episode), class: "btn btn-light border" %>
        <% else %>
            <%= link_to "Cancel", channel_path(@channel), class: "btn btn-light border" %>
        <% end %>
    </div>
<% end %>

app/views/episodes/_other_episodes_from_channel.html.erb
<% @episodes_from_channel.includes(:comments).each do |episode| %>
    <%= link_to channel_episode_path(@channel, episode), title: episode.title, class: "text-decoration-none" do %>
        <div class="card border-0 p-0 m-0">
            <%# check if episode image is present, else display default image %>
            <% if episode.image.attached? %>
                <%= image_tag(episode.image, class: "card-img-top rounded-3") %>
            <% else %>
                <%= image_tag('default-episode-image.jpg', class: "card-img-top rounded-3") %>
            <% end %>  
            <div class="card-body px-0">
                <h5 class="card-title fw-bold" style="font-size: 1rem;"><%= episode.title.truncate(65) %></h5>
                <p class="card-text text-secondary"><small><span><%= pluralize(number_with_delimiter(200000, delimiter: ','), 'view') %></span> <span class="mx-1">•</span> <span><%= time_ago_in_words(episode.created_at) %> ago</span></small></p>
            </div>
        </div>
    <% end %>
<% end %>

app/views/episodes/_save_episode_modal.html.erb
<!-- Save episode Modal -->
<div class="modal fade" id="saveEpisodeModal" tabindex="-1" aria-labelledby="saveEpisodeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Save episode to...</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'save_to_playlist', channel: @channel, episode: @episode, user: current_user if user_signed_in? %>
      </div>
    </div>
  </div>
</div>

app/views/episodes/_save_to_playlist.html.erb
<%= form_with model: [@channel, @episode] do |f| %>

    <%= render 'layouts/errors', f: f %>
    
    <div class="mb-3" data-controller="tom-select-playlist">
        <h6><%= f.label :Select_playlists, class: "form-label" %></h6>
        <%= f.select :playlist_ids, user.playlists.pluck(:name, :id), {}, { multiple: true, id: "select-playlists" } %>
    </div>

    <div class="mb-3">
        <p><%= link_to "Create new playlist", '#' %></p>
    </div>

    <div class="mb-3">
        <%= f.button "Save", class: "btn btn-success btn-sm" %>
        <button type="button" class="btn btn-light border btn-sm" data-bs-dismiss="modal">Cancel</button>
    </div>
<% end %>

app/views/episodes/edit.html.erb
<% provide(:title, "Edit episode") %>
<div class="container">
    <h1>Edit Episode</h1>

    <%= render 'form', channel: @channel, episode: @episode %>
</div>

app/views/episodes/index.html.erb
<% provide(:title, "#{@channel.name}'s episodes".html_safe) %>

<!-- layout for channel page and subpages and subpages i.e channels home, episodes, subscriptions etc.. -->
<%= render 'channels/shared/channel_layout' %>

app/views/episodes/new.html.erb
<% provide(:title, "New episode") %>
<div class="container">
    <h1>New Episode</h1>

    <%= render 'form', channel: @channel, episode: @episode %>
</div>

app/views/episodes/show.html.erb
<% provide(:title, @episode.title) %>

<div class="container py-4" style="max-width: 97vw">
  <div class="row">
    <div class="col-md-8">
      <!-- episode image and player -->
      <div class="position-relative">
        <% if @episode.image.attached? %>
          <%= image_tag(@episode.image, class: "img-fluid rounded rounded-4") %>
        <% else %>
          <%= image_tag('default-episode-image.jpg', class: "img-fluid rounded rounded-4") %>
        <% end %>
        <%= content_tag(:div, "", class: "container shk position-absolute bottom-0 start-50 translate-middle", data: {
          controller: "podcast", 
          podcast_title: @episode.title,
          podcast_url: url_for(@episode.audio),
          podcast_artist: @episode.user.username,
          podcast_cover: url_for(@channel.cover_image)
        }) %>
      </div>
      <!-- episode image and player ends -->
      
      <!-- episode title and actions -->
      <div class="metadata my-3">
        <h1 class="fs-5 fw-bold"><%= @episode .title %></h1>
        <div class="d-flex align-items-center">
          <div class="d-flex mt-1 align-items-center">

            <div class="d-flex">
              <%= link_to image_tag(@channel.avatar, size: "50x50", class: "rounded-circle rounded-circle border border-dark border-2", alt: "Episode channel", title: "Episode channel"), @channel %>
              <div class="align-self-end" style="margin-left: -23px;">
                <%= link_to image_tag('avatar.jpg', size: "30x30", class: "rounded-circle border border-warning border-2", alt: "Channel user", title: "Channel owner"), '#' %>
              </div>
            </div>

            <div class="ms-2 mt-3">
              <div><%= link_to @channel.name, @channel, class: "text-dark text-decoration-none mb-0 pb-0" %></div>
              <p class="text-secondary"><small><%= pluralize(number_with_delimiter(@channel.subscribed_users.count), 'subscriber') %></small></p>
            </div>

            <div class="ms-2"><%= render 'subscriptions/subscription_button', subscribable: @channel if user_signed_in? && @episode.user != current_user %></div>

          </div>

          <div class="d-flex ms-auto">

            <div><%= render 'likes/like_button', likeable: @episode %></div>

            <div class="ms-2">
              <%= link_to '#', class: "btn btn-light border rounded-5" do %>
                <i class="bi bi-share"></i>
                Share
              <% end %>
            </div>

            <div class="ms-2">
              <%= link_to rails_blob_path(@episode.audio, disposition: 'attachment'), class: "btn btn-light border rounded-5" do %>
                <i class="bi bi-download"></i>
                Download
              <% end %>
            </div>

            <div class="ms-2">
              <%= link_to '#', class: "btn btn-light border rounded-5", type: "button", data: { "bs-toggle": "modal", "bs-target": "#saveEpisodeModal" } do %>
                <i class="bi bi-folder-plus"></i>
                Save
              <% end %>
            </div>
          </div>
        </div>
        <!-- episode title and actions end -->

        <!-- description box -->
        <div class="description-box p-3 rounded-4" style="background: #f5f5f5;">
          <%= pluralize(number_with_delimiter(20000), 'listen') %> •
          <%= time_ago_in_words(@episode.created_at) %> ago
          <div class="description mb-3">
            <%= @episode.description.truncate(390) %>
          </div>
          
          <!-- episode tags -->
          <% unless @episode.tags.blank? %>
            Tags: 
            <% @episode.tags.each do |tag| %>
              <%= link_to '#', class: "my-2 text-decoration-none" do %>
                #<%= tag.name %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <!-- description box ends -->
        
        <!-- episode tags end -->

        <!-- comments section -->
        <section class="comments mt-3">
          <div class="header">
            <%= pluralize(number_with_delimiter(@episode.comments.count, delimiter: ","), 'comment') %>

            <!-- comments filter -->
            <span class="dropdown">
              <button class="btn btn-transparent" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-filter-left"></i>
                Sort by
              </button>
              <ul class="dropdown-menu dropdown-menu">
                <li><a class="dropdown-item active" href="#">Top comments</a></li>
                <li><a class="dropdown-item" href="#">Newest first</a></li>
              </ul>
            </div>
          </span>
          <!-- comments filter ends -->

          <!--comments form-->
          <div class="d-flex mt-3">
            <div class="me-3" style="width: 45px; height: 45px;"><%= image_tag(current_user.avatar, class: "img-fluid rounded-circle") if current_user.avatar.attached? %></div>
            <div class="w-100">
              <%= render partial: 'comments/form', locals: { commentable: @episode, comment: @comment, parent: nil, channel: @commentable.channel } %>
            </div>
          </div>
          <!-- comments form ends -->

          <!-- indivual comment -->
          <%= render @episode.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
          <!-- indivual comment ends -->

        </section>
        <!-- comments section ends -->
      </div>
    </div>

    <!-- Episode show page sidebar -->
    <div class="col-md-4">
      <aside class="epsiode-sidebar">
        <!-- sidebar tags -->
        <div>
          <%= link_to  '#', class: "btn btn-sm btn-light border active rounded-3 me-2" do %>
            From <%= @channel.name %>
          <% end %>
          <%= link_to 'Related', related_episodes_path(@channel, @episode), class: "btn btn-sm rounded-3 btn-light border me-2" %>
        </div>
        <!-- sidebar scrollable tags end -->

        <!-- List of other episodes from channel (10) -->
        <div class="mt-3">
          <% if action_name == 'show' %>
            <%= render 'other_episodes_from_channel' %>
          <% else %>
            bcdkbcd
          <% end %>
        </div>
        <!-- list of other episodes from channel ends -->
        
      </aside>
    </div>
  </div>
</div>

<%= render 'save_episode_modal' %>