config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  resources :channels do
    resources :episodes do
      resources :comments do
        resources :comments
      end
    end
    resources :playlists
  end

  # resources :comments do
  #   resources :comments
  # end

  resources :tags, only: :create
  resources :likes, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  resources :playlists
  
  get '/@:username', to: 'profiles#show', as: :profile
  get '/@:username/edit', to: 'profiles#update', as: :edit_profile

  put '/@:username', to: 'profiles#update'

  get '/@:username/subscriptions', to: 'profiles#user_subscriptions', as: :user_subs
  get '/@:username/about', to: 'profiles#about_user', as: :about_user
  get '/@:username/likes', to: 'profiles#user_likes', as: :user_likes
  get '/@:username/likes/comments', to: 'profiles#user_comment_likes', as: :user_comment_likes

  get '/channels/:id/channels', to: 'channels#owned_channels', as: :owned_channels
  get '/channels/:id/subscriptions', to: 'channels#channel_subscriptions', as: :channel_subs
  get '/channels/:id/about', to: 'channels#about_channel', as: :about_channel
  
  get '/channels/:channel_id/episodes/:id/related', to: 'episodes#related_episodes', as: :related_episodes

  get '/library', to: 'profiles#library', as: :library
  get '/history', to: 'profiles#history', as: :history
  get '/trending', to: 'profiles#trending', as: :trending
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user
  before_action :find_channel, only: [:user_likes, :user_comment_likes]

  def show

  end

  def edit
  end

  def update
    if @user.update(profile_params)
      respond_to do |format|
        format.html { redirect_to profile_path(current_user.username), notice: 'Profile updated.' }
        # format.turbo_stream
      end
    else
      flash[:alert] = current_user.errors.full_messages.join(", ")
      redirect_to profile_path(current_user.username)
    end
  end

  def user_channels
    @channels ||= @user.channels.includes(:episodes)
  end

  def user_subscriptions
    @subscriptions = @user.subscribed_channels
  end

  def about_user
    
  end

  def library
    
  end

  def user_likes
    @likes = @user.liked_episodes
  end

  def user_comment_likes
    render 'profiles/user_likes'
  end

  def trending
  end

  def history
  end

  private

  def profile_params
    params.require(:user).permit(:firstname, :lastname, :bio, :email, :avatar, :username)
  end
  
  def find_user
    @user ||= User.find_by(username: params[:username])
  end

  def find_channel
    @channel ||= @user.channels
  end

  def find_episodes
    @channel ||= @user.episodes
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/page_contents/_about_user_content.html.erb
<div class="container">
    <p><%= simple_format(@user.bio) %></p>
</div>

app/views/profiles/page_contents/_profile_show_content.html.erb
<div class="container">
    <%= render @user.channels %>
</div>

app/views/profiles/page_contents/_user_likes_content.html.erb
<div class="container">
    <div class="my-3">
        <span><%= link_to 'Episode likes', user_likes_path(@user.username), class: "btn btn-light border rounded-3 #{ 'active' if controller_name == 'profiles' && action_name == 'user_likes'}" %></span>
        <span><%= link_to 'Comment likes', user_comment_likes_path(@user.username), class: "btn btn-light border rounded-3 #{ 'active' if controller_name == 'profiles' && action_name == 'user_comment_likes'}" %></span>
    </div>

    <% if controller_name == 'profiles' && action_name == 'user_likes' %>
        <%= render @likes %>
    <% elsif controller_name == 'profiles' && action_name == 'user_comment_likes' %>
        <%= render @likes %>
    <% end %>
</div>

app/views/profiles/page_contents/_user_subscriptions_content.html.erb
<div class="container">
    <%= render @subscriptions %>
</div>